[rogue]
# class data ------------
etype = "rogue"
stamina = 11
lv_hp = [8, 9, 11, 12, 14, 15, 17, 18, 20]
position = [5, 1]
# card ------------------
[[rogue.cards]]
name = "slash"
initiative = 12
level = 1
[[rogue.cards.top]]
action = 'Move'
range = 3
fly = true
[[rogue.cards.bot]]
action = 'Move'
range = 3
fly = true
# card ------------------
[[rogue.cards]]
name = "hack"
initiative = 32
level = 1
[[rogue.cards.top]]
action = 'Attack'
damage = 2
[[rogue.cards.bot]]
action = 'Move'
range = 6
fly = true
